CREATE TABLE jogador(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(30) NOT NULL
);

CREATE TABLE ranking(
    id INTEGER PRIMARY KEY,
    pontuacao INTEGER(10) DEFAULT (0),
    CONSTRAINT fk_id_jogador FOREIGN KEY (id) REFERENCES jogador(id)
	ON DELETE CASCADE
);

CREATE TABLE dificuldade(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nivel VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE pergunta(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_nivel INTEGER NOT NULL,
    enunciado VARCHAR(500) NOT NULL,
    alternativa1 VARCHAR(50) NOT NULL,
    alternativa2 VARCHAR(50) NOT NULL,
    alternativa3 VARCHAR(50) NOT NULL,
    resposta VARCHAR(50) NOT NULL,
    CONSTRAINT fk_id_nivel FOREIGN KEY (id_nivel) REFERENCES dificuldade(id)
	ON DELETE CASCADE
);

CREATE TRIGGER TRG_DELETE_PLAYER
BEFORE DELETE ON ranking
FOR EACH ROW
BEGIN
		DELETE FROM jogador WHERE jogador.ID = OLD.ID;
END;